blueprint:
  name: Unavailable Devices Monitor
  description: Notify when devices become unavailable and when they recover.
  domain: automation
  input:
    excluded_entities:
      name: Excluded entities
      description: Entities to ignore
      default: []
      selector:
        entity:
          multiple: true
    monitored_domains:
      name: Monitored domains
      description: Domains to monitor (e.g., sensor, switch)
      default:
        - sensor
        - switch
        - light
        - binary_sensor
      selector:
        select:
          multiple: true
          options:
            - value: sensor
              label: Sensor
            - value: switch
              label: Switch
            - value: light
              label: Light
            - value: binary_sensor
              label: Binary sensor
            - value: climate
              label: Climate
            - value: lock
              label: Lock
            - value: cover
              label: Cover
            - value: camera
              label: Camera
            - value: media_player
              label: Media player
            - value: vacuum
              label: Vacuum
    unavailable_for:
      name: Unavailable for
      description: How long the device must be unavailable before notifying (duration, e.g. 00:05:00)
      default: "00:05:00"
      selector:
        duration: {}
    enable_recovery:
      name: Enable recovery notifications
      description: Send a notification when the device comes back online
      default: true
      selector:
        boolean: {}

# Blueprint variables — keep inputs out of Jinja templates, then evaluate templates against them
variables:
  entity_id: "{{ trigger.entity_id }}"
  domain: "{{ trigger.entity_id.split('.')[0] }}"
  name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
  excluded_entities: !input excluded_entities
  monitored_domains: !input monitored_domains
  unavailable_for: !input unavailable_for
  enable_recovery: !input enable_recovery
  excluded: "{{ entity_id in excluded_entities }}"
  domain_allowed: "{{ domain in monitored_domains }}"

mode: parallel
max: 20

trigger:
  - platform: state

conditions:
  - condition: template
    value_template: "{{ not excluded and domain_allowed }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'unavailable' }}"
        sequence:
          - delay: "{{ unavailable_for }}"
          - condition: template
            value_template: "{{ states(entity_id) == 'unavailable' }}"
          - service: logbook.log
            data:
              name: "Device unavailable"
              message: "{{ name }} is unavailable"
              entity_id: "{{ entity_id }}"
          - service: notify.mobile_app_adelins_iphone
            data:
              title: "⚠️ Device unavailable"
              message: >-
                {{ name }} has been unavailable for {{ unavailable_for }}.
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.from_state is not none
                 and trigger.from_state.state == 'unavailable'
                 and trigger.to_state.state != 'unavailable'
                 and enable_recovery }}
        sequence:
          - service: logbook.log
            data:
              name: "Device recovered"
              message: "{{ name }} is back online"
              entity_id: "{{ entity_id }}"
          - service: notify.mobile_app_adelins_iphone
            data:
              title: "✅ Device recovered"
              message: "{{ name }} is back online."
alias: Unavailable Devices Monitor
description: ""