blueprint:
monitored_domains: !input monitored_domains
critical_domains: !input critical_domains
excluded_entities: !input excluded_entities
unavailable_for: !input unavailable_for
aggregation_window: !input aggregation_window
rate_limit: !input rate_limit
notification_mode: !input notification_mode


domain: "{{ trigger.entity_id.split('.')[0] }}"


condition:
- condition: template
value_template: "{{ domain in monitored_domains }}"


action:
- delay: !input unavailable_for


- variables:
unavailable_entities: >
{{ states
| selectattr('domain', 'eq', domain)
| selectattr('state', 'eq', 'unavailable')
| rejectattr('entity_id', 'in', excluded_entities)
| map(attribute='entity_id')
| list }}


- condition: template
value_template: "{{ unavailable_entities | length > 0 }}"


- wait_for_trigger:
- platform: event
event_type: state_changed
timeout: !input aggregation_window
continue_on_timeout: true


- variables:
count: "{{ unavailable_entities | length }}"


severity: >
{% if domain in critical_domains %}emergency
{% elif count >= 5 %}critical
{% elif count >= 2 %}warning
{% else %}info
{% endif %}


severity_icon: >
{% if severity == 'emergency' %}🔴
{% elif severity == 'critical' %}🟠
{% elif severity == 'warning' %}🟡
{% else %}🟢
{% endif %}


entity_lines: >
{{ unavailable_entities
| map('regex_replace', '^(.*)$', '- [\\1](/config/entities/\\1) — {{ now().strftime("%H:%M") }}')
| join('\\n') }}


- choose:


# Persistent notification
- conditions:
- condition: template
value_template: "{{ notification_mode in ['persistent','both'] }}"
sequence:
- service: persistent_notification.create
data:
notification_id: "unavailable_{{ domain }}"
title: "{{ severity_icon }} {{ domain | title }} unavailable ({{ severity | upper }})"
message: >
{{ count }} entities unavailable:\n\n{{ entity_lines }}


# Push notification
- conditions:
- condition: template
value_template: >
{{ notification_mode in ['push','both']
and (domain in critical_domains
or severity in ['critical','emergency']
or this.last_triggered is none
or (now() - this.last_triggered) > rate_limit) }}
sequence:
- service: !input notify_service
data:
title: "{{ severity_icon }} {{ domain | title }} unavailable"
message: "{{ count }} entities unavailable ({{ severity }})"


mode: restart
